### ISSUE TITLE
test run fails due to wrong port number being used

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#15]
I try to run a test ..
![image](https://user-images.githubusercontent.com/8490792/125046689-8d006500-e09e-11eb-82df-a960c47a83d6.png)
The URL for the above page is http://192.168.40.53:8000/_wave/configuration.html?token=89873f18-e08d-11eb-966a-0242ac110002&resume=c4386e52-e088-11eb-a85e-0242ac110002

When I start the session, I get the starting page and then it attempts to transition to the following URL 

https://192.168.40.53:8443/avc_15_30_60-cenc-2021-06-11-local/playback-of-encrypted-content-https__t1-cenc.html?token=89873f18-e08d-11eb-966a-0242ac110002&timeout=300000&https_port=8443&web_root=/_wave/&mode=auto&&&redirect_time=5

There's nothing listening on port 8443 so this fails.

Where has port 8443 come from?

To be clear, this is a freshly updated installation as of this morning.

**Comment by jpiesing** [comment]
Sequential track playback is fine but that uses an http: URL. This is probably the first time I've run a test that uses an https: URL.

**Comment by louaybassbouss** [comment]
> Sequential track playback is fine but that uses an http: URL. This is probably the first time I've run a test that uses an https: URL.

@jpiesing https is required because EME works in some Browser only if page is loaded via https (or localhost). This is why `https` is included in the filename and the test runner switches automatically to `https` for those tests (first run http tests and then run https tests because if https is loaded first, you cannot forward back to http for security reasons). 
The port `8443` was not added to the docker-compose.yml in dpctf-deploy I just fixed and tested on my side it works fine. can you try again? 
PS: in the first time the https page is loaded, you need to accept the security exception related to SSL certificate in the browser.

**Comment by jpiesing** [comment]
> @jpiesing https is required because EME works in some Browser only if page is loaded via https (or localhost).

I know.

> This is why `https` is included in the filename and the test runner switches automatically to `https` for those tests (first run http tests and then run https tests because if https is loaded first, you cannot forward back to http for security reasons).

That makes sense to me.

> The port `8443` was not added to the docker-compose.yml in dpctf-deploy I just fixed and tested on my side it works fine. can you try again?

I just updated my local installation but it still fails.

> PS: in the first time the https page is loaded, you need to accept the security exception related to SSL certificate in the browser.

It's not getting this far.There's nothing listening on port 8443 or 443 on either localhost or 192.168.40.53.

**Comment by FritzHeiden** [comment]
The current docker-compose.yml specifies port 8443. Did you pull the changes to your local dpctf-deploy repository? Does your local docker-compose.yml contain https://github.com/cta-wave/dpctf-deploy/blob/master/docker-compose.yml#L10?  
With this change, rerunning `docker-compose up` should open port 8443.

**Comment by louaybassbouss** [comment]
@jpiesing please let us know when you tested and you still face issues

**Comment by jpiesing** [comment]
Seems to work OK-ish on my phone and a PC.
